<div class="block-header">
    <h2 class="breadcrumb">CHANGELOGS</h2>
</div>
<div class="row clearfix">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0.2 <small>2018-07-27</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>Fixed bugs in firefox and in video thumbnail.</li>
                </ul>
            </div>
        </div>
    </div>
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0.1 <small>2018-07-26</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>Fixed bugs.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0 <small>2018-07-20</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>First release.</li>
                </ul>
            </div>
        </div>
    </div>
</div>